"""add strategy and watchlist references to trades

Revision ID: 295b55f48a81
Revises: 40fdd4e3f946
Create Date: 2025-12-21 18:17:03.418755

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295b55f48a81'
down_revision: Union[str, None] = '40fdd4e3f946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Simplified for SQLite - no foreign keys (not enforced in SQLite by default anyway)
    op.add_column('trades', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('watchlist_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('exit_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trades_watchlist_id'), 'trades', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_watchlist_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_column('trades', 'exit_reason')
    op.drop_column('trades', 'watchlist_id')
    op.drop_column('trades', 'strategy_id')
    # ### end Alembic commands ###
