"""add autonomous trader tables

Revision ID: 40fdd4e3f946
Revises: 9e502ac1a683
Create Date: 2025-12-21 18:16:30.731691

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fdd4e3f946'
down_revision: Union[str, None] = '9e502ac1a683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('entry_criteria', sa.JSON(), nullable=False),
    sa.Column('exit_criteria', sa.JSON(), nullable=False),
    sa.Column('risk_management', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_strategies_id'), 'trading_strategies', ['id'], unique=False)
    op.create_index(op.f('ix_trading_strategies_is_active'), 'trading_strategies', ['is_active'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_analyzed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='watchlistpriority'), nullable=True),
    sa.Column('status', sa.Enum('WATCHING', 'ANALYZING', 'TRADED', 'REMOVED', name='watchliststatus'), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_status'), 'watchlist', ['status'], unique=False)
    op.create_index(op.f('ix_watchlist_symbol'), 'watchlist', ['symbol'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('event_type', sa.Enum('EARNINGS', 'NEWS', 'SENTIMENT_CHANGE', 'TECHNICAL_SIGNAL', 'VOLUME_SPIKE', 'PRICE_ALERT', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='eventseverity'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('impact_assessment', sa.String(), nullable=True),
    sa.Column('action_taken', sa.Enum('NONE', 'EXIT_FULL', 'EXIT_PARTIAL', 'ADJUST_STOP', 'TAKE_PROFIT', 'HOLD', 'OTHER', name='actiontaken'), nullable=True),
    sa.Column('related_trade_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['related_trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_events_event_type'), 'market_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_market_events_id'), 'market_events', ['id'], unique=False)
    op.create_index(op.f('ix_market_events_related_trade_id'), 'market_events', ['related_trade_id'], unique=False)
    op.create_index(op.f('ix_market_events_symbol'), 'market_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_events_timestamp'), 'market_events', ['timestamp'], unique=False)
    op.create_table('strategy_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('PARAMETER_CHANGE', 'NEW_RULE', 'CRITERIA_UPDATE', 'RISK_ADJUSTMENT', 'STYLE_CHANGE', name='adjustmenttype'), nullable=False),
    sa.Column('created_by', sa.Enum('REFLECTION', 'MANUAL', 'AUTO', name='adjustmentcreator'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('performance_before', sa.JSON(), nullable=True),
    sa.Column('performance_after', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['trading_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_adjustments_id'), 'strategy_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_adjustments_strategy_id'), 'strategy_adjustments', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_adjustments_timestamp'), 'strategy_adjustments', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_adjustments_timestamp'), table_name='strategy_adjustments')
    op.drop_index(op.f('ix_strategy_adjustments_strategy_id'), table_name='strategy_adjustments')
    op.drop_index(op.f('ix_strategy_adjustments_id'), table_name='strategy_adjustments')
    op.drop_table('strategy_adjustments')
    op.drop_index(op.f('ix_market_events_timestamp'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_symbol'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_related_trade_id'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_id'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_event_type'), table_name='market_events')
    op.drop_table('market_events')
    op.drop_index(op.f('ix_watchlist_symbol'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_status'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_trading_strategies_is_active'), table_name='trading_strategies')
    op.drop_index(op.f('ix_trading_strategies_id'), table_name='trading_strategies')
    op.drop_table('trading_strategies')
    # ### end Alembic commands ###
